---
- name: Get Facts
  hosts: cisco
  gather_facts: false
  vars:
    acl: true
  tasks:
    - name: Gather legacy and resource facts
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: all

    - name: Debug facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Debug facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Configure http timeout policy
      cisco.ios.ios_config:
        lines:
          - ip http timeout-policy idle 300 life 3000 requests 30
          - ip ssh server algorithm mac hmac-sha2-256
          - no ip ssh server algorithm mac hmac-sha1
          - login block-for 900 attempts 10 within 120
          - login on-failure log
          - login on-success log

    - name: Configure line con 0
      cisco.ios.ios_config:
        lines:
          - privilege level 15
          - exec-timeout 5 0
          - logging synchronous
        parents: line con 0

    - name: Configure SNMP
      cisco.ios.ios_config:
        lines:
          - no snmp-server host 137.232.96.48 version 2c public
          - snmp-server host 137.232.96.48 version 3 auth 3maw


    - name: Load new acl into device
      when: acl == true
      cisco.ios.ios_config:
        parents: ip access-list extended MANAGEMENT_NET
        lines:
          - 10 permit ip 192.168.1.0 0.0.0.255 any log
        before: no ip access-list extended test
        match: exact


    - name: apply to vty lines
      when: acl == true
      cisco.ios.ios_config:
        parents: line vty 0 15
        lines:
          - access-class MANAGEMENT_NET in vrf-also

